export const profile = {
  name: "Aakash Sathish Shetty",
  title: "Software Engineer • Full-stack Developer • Backend Engineer",
  location: "Tempe, AZ (open to relocation)",
  email: "aakashind45@gmail.com",
  phone: "602-573-3526",
  links: {
    linkedin: "https://linkedin.com/in/aakash-s-shetty",
    github: "https://github.com/Aakash3040",
    medium: "https://medium.com/@aakashind45",
    resume: "/resume.pdf",
  },
  counters: [
    { value: 87, label: "Build time reduction", suffix: "%" },
    { value: 18.7, label: "Efficiency improvement", suffix: "%" },
    { value: 3, label: "Years of experience", suffix: "+" },
    { value: 72, label: "Deployment speed-up", suffix: "%" },
  ],
  projects: [
    {
      tag: "Reinforcement Learning",
      tag2: "Python",
      title: "RL Agent for Pacman",
      desc: "Implemented REINFORCE and Actor-Critic algorithms with performance tuning and reproducibility testing.",
      linkText: "View Code",
      link: "https://github.com/Aakash3040/3.Reinforcement",
      tech: ["python", "numpy"],
    },
    {
      tag: "Machine Learning",
      tag2: "NLP",
      title: "Mental Health Crisis Prediction",
      desc: "Built an end-to-end ML pipeline in Python to classify crisis signals from social media text; compared TF-IDF vs. embedding-based features across supervised models.",
      tech: ["python"],
    },
    {
      tag: "Cloud Offloading",
      tag2: "Distributed Systems",
      title: "Optimal Joint Scheduling & Cloud Offloading",
      desc: "Designed a distributed mobile-cloud system improving computational efficiency by 24.7% (SPRINGER ERCICA 2020).",
      linkText: "View Published Article",
      link: "https://www.nmit.ac.in/ercica/pdf/Ebook/2020_Book_Volume%202.pdf",
      tech: ["java", "android"],
    },
  ],
  experience: [
    {
      company: "BusinessRate",
      role: "Software Engineer",
      dates: "May 2026 - Aug 2026",
      bullets: [
        "Built a full-stack mail tracking integration on Lob's REST API (/events endpoint), combining real-time sync with scheduled backfill sync, surfaced on an internal dashboard.",
        "Paired with another developer on “Milestones,” a cart-and-checkout UI feature using Node.js, TypeScript, JavaScript, and Next.js.",
        "Designed 8 new PostgreSQL tables across schemas to support the integration; resolved schema issues on existing tables.",
        "Reviewed and merged 6-7 pull requests a week from 2 teammates as part of the team's code review process.",
      ],
      tech: ["typescript", "nodejs", "react", "postgresql"],
    },
    {
      company: "SowFin",
      role: "AI Software Engineer",
      dates: "Oct 2025 - May 2026",
      bullets: [
        "Shipped backend APIs in Python integrating Google Drive, OneDrive, and Notion for document access.",
        "Built React features for onboarding/authentication: work-email verification, OTP, password recovery.",
        "Owned features end-to-end through Docker deployment on AWS EC2; reduced build time from 40 → 5 minutes (~87%).",
        "Developing a secure Data Room module with intuitive workflows, access control, and reliability.",
      ],
      tech: ["python", "react", "docker", "amazonwebservices", "postgresql"],
    },
    {
      company: "Harman Connected Services",
      role: "Software Engineer",
      dates: "Dec 2020 - Dec 2023",
      bullets: [
        "Built and maintained backend services handling concurrent user requests and high-frequency DB updates.",
        "Improved deployment workflows and reduced deployment by 72%.",
        "Optimized SQL queries and backend logic, improving data access efficiency by 18.7%.",
        "Collaborated with engineers, QA, and product teams in Agile sprints; resolved critical bugs and shipped features.",
      ],
      tech: ["java", "spring", "mysql", "docker", "jenkins"],
    },
    {
      company: "Drona Automations",
      role: "Intern",
      dates: "Jun 2019 - July 2019",
      bullets: [
        "Built prototype of an autonomous robotic system integrating sensors and Bluetooth communication.",
        "Developed Android app for real-time navigation, control, and data visualization.",
      ],
      tech: ["android", "arduino", "bluetooth"],
    },
  ],
  skills: {
    Languages: ["Python", "JavaScript", "TypeScript", "Java", "SQL", "C/C++", "Perl"],
    Frameworks: ["React", "Next.js", "Node.js", "Django", "MVC"],
    Backend: [
      "RESTful APIs",
      "PostgreSQL",
      "MS SQL Server",
      "MySQL",
      "Authentication/Authorization",
      "Unit & Functional Testing",
    ],
    DevOps: ["Docker", "Git", "CI/CD", "AWS (EC2, S3)"],
    Concepts: [
      "OOP",
      "Data Structures",
      "Algorithms",
      "API Design",
      "Scalability",
      "Distributed Systems",
    ],
  },
  education: [
    {
      school: "Arizona State University",
      degree: "M. S. Computer Science",
      dates: "Jan 2024 - May 2025",
    },
    {
      school: "Nitte Meenakshi Institute of Technology",
      degree: "B.E Computer Science",
      dates: "Aug 2016 - Sep 2020",
    },
  ],
};
